version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-knock-in
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana-knock-in
    ports:
      - "3000:3000"
    volumes:
      - ./ssl:/etc/grafana/ssl:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/cert.pem
      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/key.pem
    depends_on:
      - prometheus
      - loki
    restart: always

  loki:
    image: grafana/loki:3.7.0
    container_name: loki-knock-in
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - ./ssl:/etc/loki/ssl:ro
      - loki-data:/loki
    restart: always

volumes:
  loki-data: